import { SelectItem } from "primereact/selectitem"

export const convertSelectOptions: SelectItem[] = [
  { label: "AVIF", value: "avif" },
  { label: "DZ", value: "dz" },
  { label: "FITS", value: "fits" },
  { label: "GIF", value: "gif" },
  { label: "HEIF", value: "heif" },
  { label: "INPUT", value: "input" },
  { label: "JPEG", value: "jpeg" },
  { label: "JPG", value: "jpg" },
  { label: "JP2", value: "jp2" },
  { label: "JXL", value: "jxl" },
  { label: "MAGICK", value: "magick" },
  { label: "OPENSLIDE", value: "openslide" },
  { label: "PDF", value: "pdf" },
  { label: "PNG", value: "png" },
  { label: "PPM", value: "ppm" },
  { label: "RAW", value: "raw" },
  { label: "SVG", value: "svg" },
  { label: "TIFF", value: "tiff" },
  { label: "TIF", value: "tif" },
  { label: "V", value: "v" },
  { label: "WEBP", value: "webp" },
]
